### ISSUE TITLE
some wrong with the loading of lib file

### ISSUE THREAD

**Issue by zhangxulong** [ssky87/iflytek_sdk_python#3]
@ssky87  there is some wrong with the lib file ? I cannot load it on my mac.

Traceback (most recent call last):
  File "/Users/zhangxulong/Project/testPy/tts.py", line 98, in <module>
    text_to_speech('科大讯飞还是不错的','xx.wav')
  File "/Users/zhangxulong/Project/testPy/tts.py", line 35, in text_to_speech
    cur = cdll.LoadLibrary(BASEPATH + '/x64/libmsc.so')
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/zhangxulong/Project/testPy/x64/libmsc.so, 6): no suitable image found.  Did find:
	/Users/zhangxulong/Project/testPy/x64/libmsc.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/zhangxulong/Project/testPy/x64/libmsc.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Traceback (most recent call last):
  File "/Users/zhangxulong/Project/testPy/tts.py", line 98, in <module>
    text_to_speech('科大讯飞还是不错的','xx.wav')
  File "/Users/zhangxulong/Project/testPy/tts.py", line 35, in text_to_speech
    cur = cdll.LoadLibrary(BASEPATH + '/x64/libmsc.so')
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/zhangxulong/Project/testPy/x64/libmsc.so, 6): no suitable image found.  Did find:
	/Users/zhangxulong/Project/testPy/x64/libmsc.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/zhangxulong/Project/testPy/x64/libmsc.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by ssky87** [comment]
Sorry I didn't test on mac.

OSError: dlopen(/Users/zhangxulong/Project/testPy/x64/libmsc.so, 6): no suitable image found. 

Maybe the lib can't run on mac

**Comment by zhangxulong** [comment]
yes I ran it on ubuntu is okay. but the result is error.  I turn to use the baidu speech, the result is good!
